sudo: required

language: go

services:
  - docker

go:
  - master

install:
  - git clone https://github.com/antontsv/awesome-shell
  - sudo awesome-shell/INSTALL

script: sudo scripts/build-container
