sudo: required

language: go

services:
  - docker

go:
  - master

install:
  - git clone https://github.com/antontsv/awesome-shell
  - sudo awesome-shell/INSTALL
  - scripts/build-container
  - ls
  - docker run --name fc -p 127.0.0.1:80:3031 -d flash-cards
  - sleep 15
  - docker logs --details fc
  - docker ps -a

script: curl http://127.0.0.1

after_script:
  - docker stop fc
  - docker rm fc
